[package]
name = "centaurus"
version = "0.1.0"
authors = ["woshilapin <woshilapin@tuziwo.info>"]
edition = "2018"

[dependencies]
nalgebra = "0.17.2"
serde = "1.0.89"
serde_derive = "1.0.89"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "render"
harness = false
