language: cpp

addons:
    apt:
        packages:
            - autopoint
            - libboost-dev
            - libboost-test-dev
            - libmagick++-dev

compiler:
    - clang
    - gcc

script: ./autogen.sh && ./configure && make && make check
