[package]
name = "centaurus-cli"
version = "0.1.0"
authors = ["woshilapin <woshilapin@tuziwo.info>"]
edition = "2018"

[dependencies]
centaurus = { path = "../centaurus" }
clap = "2.32.0"
image = "0.21.0"
