[package]
name = "centaurus-core"
version = "0.1.0"
authors = ["woshilapin <woshilapin@tuziwo.info>"]

[dependencies]
nalgebra = "0.15.3"

[dev-dependencies]
pretty_assertions = "0.5"
criterion = "0.2"

[[bench]]
name = "render"
harness = false
